apiVersion: v1
kind: Service
metadata:
  name: k8-gopherciser
  labels:
    app: k8-gopherciser
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      protocol: TCP
      name: k8-gopherciser
